FROM node:20

WORKDIR /app

# Install dependencies first for caching
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy everything else
COPY . .

RUN npx prisma generate

# Expose port and run dev server
EXPOSE 3000

CMD ["npm", "run", "dev"]
